### ISSUE TITLE
Can I access the dataset?

### ISSUE THREAD

**Issue by peter0512lee** [Medjed46/NPU-RGBD-Basketball-Dataset#1]
Hello, 
I need this dataset very urgent.
Can I access this dataset.
Thank you!

**Comment by breezexixixi** [comment]
Hello, have you obtained this dataset? If you have a way to download it, please contact me. Thank you very much.

**Comment by breezexixixi** [comment]
Sorry, I don't have access to that dataset.



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 2, 2025 17:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Medjed46/NPU-RGBD-Basketball-Dataset] Can I access the dataset?(#1)


Stickic-cyber left a comment (Medjed46/NPU-RGBD-Basketball-Dataset#1)
  
Hello, have you obtained this dataset? If you have a way to download it, please contact me. Thank you very much.
  
have you got the dataset? I kinda need it too, thank you!
